spring.profiles.active: dev

server.port: 12347

spring:
  application:
    name: spring-boot-kafka-cluster-producer
  kafka:
    clientId: ${ENV_APPLICATION_CLIENTID}

---

spring.profiles: dev

kafka:
  bootstrap:
    servers: ${ENV_KAFKA_BOOTSTRAP_SERVERS}
---

spring.profiles: integration
