spring.profiles.active: dev

server.port: 12347

spring:
  application:
    name: spring-boot-kafka-cluster-producer

---

spring.profiles: dev

kafka:
  bootstrap:
    servers: ${ENV_KAFKA_BOOTSTRAP_SERVERS}
---

spring.profiles: integration
