spring.profiles.active: dev

server.port: 12346

spring:
  application:
    name: spring-boot-kafka-cluster
  datasource:
    driver-class-name: ${ENV_DRIVER_CLASS_NAME}
    url: ${ENV_DATASOURCE_URL}
    username: ${ENV_DATASOURCE_SERVICE_USERNAME}
    password: ${ENV_DATASOURCE_SERVICE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

---

spring.profiles: dev


ENV_DATASOURCE_URL: jdbc:postgresql://postgres/store
ENV_DATASOURCE_SERVICE_USERNAME: dbuser
ENV_DATASOURCE_SERVICE_PASSWORD: password
ENV_DRIVER_CLASS_NAME: org.postgresql.Driver
ENV_KAFKA_BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:29092,kafka-3:39092
ENV_ZOOKEEPER_CONNECT_STRING: zookeeper-1:12181,zookeeper-2:12181,zookeeper-3:12181


---

spring.profiles: integration

