version: "3.7"
services:
  postgres:
    build: postgres
    environment:
      POSTGRES_PASSWORD: dbuser
      POSTGRES_USER: password
      POSTGRES_DB: store
  spring-boot-testcontainers:
    build: ../
    ports:
    - "12345:12345"
    links:
      - postgres
    environment:
      JAVA_HEAP_SIZE_MB: 1024
