version: "3.7"
services:
  zookeeper:
    image: "zookeeper:3.4.13"
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: "confluent/kafka:latest"
    ports:
      - "9092:9092"
    hostname: kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres:
    build: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store
    ports:
    - 5432:5432
  spring-boot-kafka-cluster:
    build: ../
    ports:
      - "12346:12346"
    links:
      - postgres
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_HEAP_SIZE_MB: 1024
      kafka.bootstrap.servers: kafka:9092
